vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.dbclient-jdbc

tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  
  - name: frontend-react-js
    init: |
      cd /frontend-react-js
      npm i

  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
      sudo apt-get update
      sudo apt-get install -y postgresql-client libpq-dev

ports:
  - name: frontend
    port: 3005
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public

    # -------- This is needed for x-ray to work so just uncomment it
  # - name: xray-daemon
    # port: 2000
    # visibility: public


